version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:6.8.0
    container_name: elasticsearch
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
