version: '3.8'
services:
  db:
    image: postgres:latest
    command: postgres -c 'max_connections=500'
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./backup:/tmp/backup
